#!/usr/bin/env python3
from flask import Flask, request
import subprocess
import logging
import re

app = Flask(__name__)

# Configure logging
log_file = 'webhook.log'
logging.basicConfig(filename=log_file, level=logging.DEBUG, format='%(asctime)s - %(levelname)s - %(message)s')

@app.route('/', methods=['POST'])
def webhook():
    try:
        data = request.json
        logging.info('Received POST request with data: %s', data)

        # Check if the alert is a MySQLDown alert
        if data['alerts'][0]['labels']['alertname'] == 'MySQLDown':
            logging.info('Received MySQLDown alert. Restarting MySQL service...')
            
            # Extract the IP address from the instance label
            instance = data['alerts'][0]['labels']['instance']
            ip_address = re.match(r'^(.*?):\d+$', instance).group(1)
            
            # Restart MySQL service on the specified server
            subprocess.run(['sudo', '-u', 'restarter', 'ssh', f'restarter@{ip_address}', 'sudo systemctl restart mysql'])
            logging.info('MySQL service restarted successfully on instance %s.', ip_address)
        else:
            logging.info('Received alert is not MySQLDown. No action taken.')
    except Exception as e:
        logging.error('An error occurred: %s', str(e))
    return '', 200

if __name__ == '__main__':
    app.run(host='0.0.0.0', port=5001)
